services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-library-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://perpus_user:perpus_password@db:5432/school_library?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=ganti_dengan_secret_acak_minimal_32_karakter_openssl
      - AUTH_TRUST_HOST=true
    volumes:
      - uploads_data:/app/public/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: school-library-db
    restart: always
    environment:
      POSTGRES_USER: perpus_user
      POSTGRES_PASSWORD: perpus_password
      POSTGRES_DB: school_library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perpus_user -d school_library"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploads_data:
